---
  - name: 检查 nginx 是否安装
    stat:
      path: "{{ nginx.install_dir }}/sbin/nginx"
    register: stat_result

  - block:
    - name: 下载 nginx 安装包
      import_tasks: download.yml
    - name: 安装 nginx
      import_tasks: install.yml
    - name: 检查 nginx 是否安装成功
      import_tasks: check.yml
    - name: 清理 nginx 安装包
      import_tasks: cleanup.yml
    when: stat_result.stat.exists == False

  - name: 输出已安装检查结果
    debug:
      msg: "nginx 已安装"
    when: stat_result.stat.exists == True