---
gcc:
  filesvr_path: deploy-base/gcc
  files:
    - cpp-4.8.5-39.el7.x86_64.rpm
    - gcc-4.8.5-39.el7.x86_64.rpm
    - glibc-devel-2.17-292.el7.x86_64.rpm
    - glibc-headers-2.17-292.el7.x86_64.rpm
    - kernel-headers-3.10.0-1062.12.1.el7.x86_64.rpm
    - libgomp-4.8.5-39.el7.x86_64.rpm
    - libmpc-1.0.1-3.el7.x86_64.rpm
    - mpfr-3.1.1-4.el7.x86_64.rpm

gcc_c:
  filesvr_path: deploy-base/gcc-c++
  files:
    - gcc-c++-4.8.5-39.el7.x86_64.rpm
    - libstdc++-devel-4.8.5-39.el7.x86_64.rpm

make:
  filesvr_path: deploy-base/make
  files:
    - make-3.82-24.el7.x86_64.rpm

perl:
  filesvr_path: deploy-base/perl
  files:
    - groff-base-1.22.2-8.el7.x86_64.rpm
    - perl-5.16.3-294.el7_6.x86_64.rpm
    - perl-Carp-1.26-244.el7.noarch.rpm
    - perl-constant-1.27-2.el7.noarch.rpm
    - perl-Encode-2.51-7.el7.x86_64.rpm
    - perl-Exporter-5.68-3.el7.noarch.rpm
    - perl-File-Path-2.09-2.el7.noarch.rpm
    - perl-File-Temp-0.23.01-3.el7.noarch.rpm
    - perl-Filter-1.49-3.el7.x86_64.rpm
    - perl-Getopt-Long-2.40-3.el7.noarch.rpm
    - perl-HTTP-Tiny-0.033-3.el7.noarch.rpm
    - perl-libs-5.16.3-294.el7_6.x86_64.rpm
    - perl-macros-5.16.3-294.el7_6.x86_64.rpm
    - perl-parent-0.225-244.el7.noarch.rpm
    - perl-PathTools-3.40-5.el7.x86_64.rpm
    - perl-Pod-Escapes-1.04-294.el7_6.noarch.rpm
    - perl-podlators-2.5.1-3.el7.noarch.rpm
    - perl-Pod-Perldoc-3.20-4.el7.noarch.rpm
    - perl-Pod-Simple-3.28-4.el7.noarch.rpm
    - perl-Pod-Usage-1.63-3.el7.noarch.rpm
    - perl-Scalar-List-Utils-1.27-248.el7.x86_64.rpm
    - perl-Socket-2.010-4.el7.x86_64.rpm
    - perl-Storable-2.45-3.el7.x86_64.rpm
    - perl-Text-ParseWords-3.29-4.el7.noarch.rpm
    - perl-threads-1.87-4.el7.x86_64.rpm
    - perl-threads-shared-1.43-6.el7.x86_64.rpm
    - perl-Time-HiRes-1.9725-3.el7.x86_64.rpm
    - perl-Time-Local-1.2300-2.el7.noarch.rpm

openssl:
  filesvr_path: deploy-base/openssl
  file: openssl-1.0.2r.tar.gz

pcre:
  filesvr_path: deploy-base/pcre
  file: pcre-8.43.tar.gz

zlib:
  filesvr_path: deploy-base/zlib
  file: zlib-1.2.11.tar.gz

nginx:
  filesvr_path: deploy-base/nginx
  file: nginx-1.16.1.tar.gz