---
- name: 获取版本
  import_tasks: download.yml
- name: 停止服务
  import_tasks: stop.yml
- name: 备份版本
  import_tasks: backup.yml
  when: inventory_hostname == groups.appservers[0]
- name: 部署版本
  import_tasks: update.yml
- name: 启动服务
  import_tasks: start.yml
- name: 清除文件
  import_tasks: cleanup.yml