---
- name: 启动服务
  shell: "source {{ group_all.home }}/.bash_profile && cd {{ server.deploy_path }} && nohup java {{ group_app.java_options }} -jar {{ group_app.deploy_file }} --spring.profiles.active={{ group_app.active_profile }} &"

- name: 检查服务进程是否启动
  shell: "ps -ef | grep {{ server.process_key }} | grep -v grep | wc -l"
  register: running_processes_count
  failed_when: running_processes_count.stdout == "0"

- name: 检查监听端口是否开启
  wait_for:
    port: "{{ group_app.server_port }}"
    delay: 5
    state: started