---
- hosts: manageservers
  gather_facts: no
  remote_user: "{{ group_all.ansible_user }}"
  any_errors_fatal: true
  tasks:
    - import_role:
        name: java
    - import_role:
        name: ansible-server-admin