---
- hosts: webservers
  gather_facts: no
  any_errors_fatal: true
  tasks:
    - import_role:
        name: nginx
      become: yes
      become_method: su
    - import_role:
        name: ansible-front
      tags: "version deploy"