---
- name: 创建下载目录
  file:
    path: "{{ group_all.home }}/downloads"
    state: directory

- name: 下载 java 压缩包
  get_url:
    url: "{{ group_all.filesvr_url }}/{{ java.filesvr_path }}/{{ java.install_file }}"
    dest: "{{ group_all.home }}/downloads/{{ java.install_file }}"
    force: yes