---
- name: 解压 java 到当前用户目录
  unarchive:
    src: "{{ home }}/downloads/{{ java.file }}"
    dest: "{{ home }}/"
    copy: no

- name: 重命名 java 文件夹
  shell: "mv {{ home }}/{{ java.unzip_dir }} {{ java.install_path }}"

- name: 设置环境变量
  template:
    src: .bash_profile
    dest: "{{ home }}/"