---
- name: 解压 java 到当前用户目录
  unarchive:
    src: "{{ group_all.home }}/downloads/{{ java.install_file }}"
    dest: "{{ group_all.home }}/"
    copy: no

- name: 重命名 java 文件夹
  shell: "mv {{ group_all.home }}/{{ java.unzip_dir }} {{ java.install_path }}"

- name: 设置环境变量
  template:
    src: .bash_profile
    dest: "{{ group_all.home }}/"