---
  - name: 创建下载目录
    file:
      path: "{{ home }}/downloads"
      state: directory

  - name: 下载 java 压缩包
    get_url:
      url: "{{ filesvr_url }}/{{ java.filesvr_path }}/{{ java.file }}"
      dest: "{{ home }}/downloads/{{ java.file }}"
      force: yes

  - name: 解压 java 到当前用户目录
    unarchive:
      src: "{{ home }}/downloads/{{ java.file }}"
      dest: "{{ home }}/"
      copy: no
  
  - name: 重命名 java 文件夹
    shell: "mv {{ home }}/{{ java.unzip_dir }} {{ java.install_path }}"

  - name: 设置环境变量
    template:
      src: .bash_profile
      dest: "{{ home }}/"

  - name: 测试 java 是否配置成功
    shell: "source {{ home }}/.bash_profile && java -version"
    register: result
    failed_when: java.version not in result.stderr

  - name: 清理 java 安装临时文件
    file:
      path: "{{ home }}/downloads/{{ java.file }}"
      state: absent