---
- name: 检查 java 是否安装
  stat:
    path: "{{ java.install_path }}"
  register: stat_result

- block:
  - name: 下载 java 安装包
    import_tasks: download.yml
  - name: 安装 java
    import_tasks: install.yml
  - name: 检查 java 是否安装成功
    import_tasks: check.yml
  - name: 清理 java 安装包
    import_tasks: cleanup.yml
  when: stat_result.stat.exists == False

- name: 输出已安装检查结果
  debug:
    msg: "java 已安装"
  when: stat_result.stat.exists == True