---
- name: 启动服务
  shell: "{{ front.nginx_install_path }}/sbin/nginx -c {{ front.deploy_path }}/conf/nginx.conf"

- name: 检查服务进程是否启动
  shell: "ps -ef | grep {{ front.deploy_path }}/conf/nginx.conf | grep -v grep | wc -l"
  register: running_processes_count
  failed_when: running_processes_count == "0"

- name: 检查监听端口是否开启
  wait_for:
    port: "{{ group_web.server_port }}"
    delay: 5
    state: started