---
- name: 查找正在运行的服务进程
  shell: "ps -ef | grep {{ front.deploy_path }}/conf/nginx.conf | grep -v grep | wc -l"
  register: running_processes_count

- name: 停止正在运行的服务进程
  shell: "{{ front.nginx_install_path }}/sbin/nginx -c {{ front.deploy_path }}/conf/nginx.conf -s quit"
  when: running_processes_count.stdout != "0"

- name: 检查服务进程是否停止
  shell: "ps -ef | grep {{ front.deploy_path }}/conf/nginx.conf | grep -v grep | wc -l"
  register: running_processes_count
  failed_when: running_processes_count.stdout != "0"

- name: 检查监听端口是否关闭
  wait_for:
    port: "{{ group_web.server_port }}"
    delay: 5
    state: stopped