---
- name: 删除旧版本
  file:
    path: "{{ front.deploy_path }}"
    state: absent

- name: 创建部署目录
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ front.deploy_path }}/site"
    - "{{ front.deploy_path }}/conf"
    - "{{ front.deploy_path }}/cert"

- name: 解压新版本
  unarchive:
    src: "{{ group_all.home }}/downloads/{{ group_web.deploy_file }}"
    dest: "{{ front.deploy_path }}/site/"
    copy: no

- name: 上传配置文件
  template:
    src: nginx.conf
    dest: "{{ front.deploy_path }}/conf/"