---
- name: 创建下载目录
  file:
    path: "{{ group_all.home }}/downloads"
    state: directory

- name: 下载部署版本
  get_url:
    url: "{{ group_all.filesvr_url }}/{{ server_admin.filesvr_path }}/{{ group_manage.deploy_file }}"
    dest: "{{ group_all.home }}/downloads/{{ group_manage.deploy_file }}"
    force: yes