---
- name: 创建下载目录
  file:
    path: "{{ home }}/downloads"
    state: directory

- name: 下载部署版本
  get_url:
    url: "{{ filesvr_url }}/{{ filesvr_path }}/{{ deploy_file }}"
    dest: "{{ home }}/downloads/{{ deploy_file }}"
    force: yes