---
- name: 创建下载目录
  file:
    path: "{{ home }}/downloads"
    state: directory

- name: 下载部署版本
  get_url:
    url: "{{ filesvr_url }}/{{ admin.filesvr_path }}/{{ admin.file }}"
    dest: "{{ home }}/downloads/{{ admin.file }}"
    force: yes