---
- name: 删除旧版本
  file:
    path: "{{ admin.deploy_path }}"
    state: absent

- name: 创建部署目录
  file:
    path: "{{ admin.deploy_path }}"
    state: directory

- name: 解压新版本
  unarchive:
    src: "{{ home }}/downloads/{{ admin.file }}"
    dest: "{{ admin.deploy_path }}"
    copy: no